cmdProbe/inputs:
  command: python3 script.py
  comparator:
    criteria: <=
    type: float
    value: "20000"
  source:
    env:
    - name: K8S_NAMESPACE
      value: online-shop
    - name: LABEL_SELECTOR
      value: app=productcatalogservice
    image: mcp-docker-dev.docker.fis.dev/amitkrdas/pod-startup-time-amd64:v3-updated
mode: Continuous
name: product-catalogue-pod-startup-time-probe
runProperties:
  attempt: 1
  initialDelay: 5s
  interval: 2s
  probeTimeout: 10s
  verbosity: debug
type: cmdProbe
